version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: alpine/helm:3.5.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "83:1b:3b:f6:38:ab:71:59:c5:13:0b:1f:d9:98:a1:df"
      - checkout
      - run:
          name: charts
          environment:
            - GITHUB_PAGES_REPO: kklab-com/registry-creds-helm
          command: wget -O - https://raw.githubusercontent.com/kklab-com/registry-creds-helm/master/publish.sh | sh
